### ISSUE TITLE
"Uncaught TypeError" thrown in console when clicking the VR glasses icon.

### ISSUE THREAD

**Issue by canxcao** [01org/websensor-vr-button#3]
Test device: Nexus 9 (Android 7.1.1) and Nexus 5

reproduce steps:
1. access to https://vrbutton.appspot.com
2. Debug it by chome://inspect
3. click the VR glasses icon.

expect result:
No error, and demo should works fine.

actual result:
"Uncaught TypeError" thrown in console.
Please refer to the attachment "vrbutton.png".
![vrbutton](https://user-images.githubusercontent.com/13044790/30467435-0d97ea3a-9a17-11e7-988c-f3a129b44c20.png)

**Comment by alexshalamov** [comment]
The code has been moved to https://github.com/intel/generic-sensor-demos/tree/master/vr-button
